# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b22469f3ee32bc01d25a10226f77a5d4cfda090c588e7302a176aa149a1a4ef20e78141e5543cb4df36326dd1209aa6cc28bf135eae7a2b397408d2fb7da739
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  
  google_address: <%= ENV["GOOGLE_ADDRESS"] %>
  google_password: <%= ENV["GOOGLE_PASSWORD"] %>
  
  
test:
  secret_key_base: 7c1a4ed76a0e696181b8b3e8968f0e00b565c24340e38b839448607e7fced678ff9e202f82dfb3fab5dd723204f7869f9c08fc19f9ab7b2fea8e07ff5f76f422

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  
  google_address: <%= ENV["GOOGLE_ADDRESS"] %>
  google_password: <%= ENV["GOOGLE_PASSWORD"] %>

  
  